"""Your migration message

Revision ID: 69e5f540e541
Revises: 6136e6d1beaa
Create Date: 2024-11-05 19:40:08.090707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e5f540e541'
down_revision = '6136e6d1beaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
