"""Add game preferences tables

Revision ID: 82ba6a0390dd
Revises: a3ac24dbd410
Create Date: 2024-10-27 12:40:00.716195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ba6a0390dd'
down_revision = 'a3ac24dbd410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('game_style', sa.String(), nullable=False),
    sa.Column('tone', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_preferences')
    # ### end Alembic commands ###
