"""Add User model and update game_preferences and saved_games

Revision ID: 9b6c9ebbaf0a
Revises: 5ebdde428e4f
Create Date: 2024-11-05 21:16:57.395020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b6c9ebbaf0a'
down_revision = '5ebdde428e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
